server:
  servlet:
    context-path: /api/v1

spring:
  application:
  name: Link Vault

  datasource:
    url: jdbc:postgresql://dpg-cqgd8q5ds78s73ccu0lg-a.oregon-postgres.render.com:5432/link_vault
    username: user
    password: 2idEqdiYgrElrTQnjw33OQ5M0K6cRBtJ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-ddl: false
    show-sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

  mvc:
    static-path-pattern: /swagger*
