spring:
  application:
  name: Link Vault

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}

            scope:
              - email
              - profile

  datasource:
    url: jdbc:postgresql://localhost:5433/link_vault
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    static-path-pattern: /swagger*
